# Use an official Node.js runtime as the base image for React
FROM node:14

# Set the working directory for React
WORKDIR /app/frontend

# Copy package.json and package-lock.json for React
COPY package*.json ./

# Install React dependencies
RUN npm install

# Copy the rest of the React application code
COPY . .

# Build the React app
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Define the command to serve the React app
CMD ["npm", "start"]
