version: "3.4"

services:
    backend:
        image: coincompanions
        build:
            context: .
            dockerfile: Dockerfile.backend
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.frontend
        ports:
            - "3000:3000"
        env_file:
            - ./frontend/.env

    database:
        image: postgres:12
        ports:
            - 5432:5432
        env_file:
            - ./backend/.env
