export const GROUP_INVITE_DECLINE_REQUEST = "GROUP_INVITE_DECLINE_REQUEST";
export const GROUP_INVITE_DECLINE_SUCCESS = "GROUP_INVITE_DECLINE_SUCCESS";
export const GROUP_INVITE_DECLINE_FAIL = "GROUP_INVITE_DECLINE_FAIL";
export const GROUP_INVITE_DECLINE_RESET = "FRIENDS_INVITE_DECLINE_RESET";

export const GROUP_CREATE_REQUEST = "GROUP_CREATE_REQUEST";
export const GROUP_CREATE_SUCCESS = "GROUP_CREATE_SUCCESS";
export const GROUP_CREATE_FAIL = "GROUP_CREATE_FAIL";
export const GROUP_CREATE_RESET = "GROUP_CREATE_RESET";

export const GROUP_LIST_REQUEST = "GROUP_LIST_REQUEST";
export const GROUP_LIST_SUCCESS = "GROUP_LIST_SUCCESS";
export const GROUP_LIST_FAIL = "GROUP_LIST_FAIL";

export const GROUP_DETAILS_REQUEST = "GROUP_DETAILS_REQUEST";
export const GROUP_DETAILS_SUCCESS = "GROUP_DETAILS_SUCCESS";
export const GROUP_DETAILS_FAIL = "GROUP_DETAILS_FAIL";
export const GROUP_DETAILS_RESET = "GROUP_DETAILS_RESET";

export const GROUP_NAME_UPDATE_REQUEST = "GROUP_NAME_UPDATE_REQUEST";
export const GROUP_NAME_UPDATE_SUCCESS = "GROUP_NAME_UPDATE_SUCCESS";
export const GROUP_NAME_UPDATE_FAIL = "GROUP_NAME_UPDATE_FAIL";
export const GROUP_NAME_UPDATE_RESET = "GROUP_NAME_UPDATE_RESET";
