export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_FRIENDS_LIST_REQUEST = "USER_FRIENDS_LIST_REQUEST";
export const USER_FRIENDS_LIST_SUCCESS = "USER_FRIENDS_LIST_SUCCESS";
export const USER_FRIENDS_LIST_FAIL = "USER_FRIENDS_LIST_FAIL";

export const USER_FRIENDS_SEARCH_REQUEST = "USER_FRIENDS_SEARCH_REQUEST";
export const USER_FRIENDS_SEARCH_SUCCESS = "USER_FRIENDS_SEARCH_SUCCESS";
export const USER_FRIENDS_SEARCH_FAIL = "USER_FRIENDS_SEARCH_FAIL";

export const USER_FRIENDS_DELETE_REQUEST = "USER_FRIENDS_DELETE_REQUEST";
export const USER_FRIENDS_DELETE_SUCCESS = "USER_FRIENDS_DELETE_SUCCESS";
export const USER_FRIENDS_DELETE_FAIL = "USER_FRIENDS_DELETE_FAIL";
export const USER_FRIENDS_DELETE_RESET = "USER_FRIENDS_DELETE_RESET";

export const USER_FRIENDS_REQUEST_LIST_REQUEST =
    "USER_FRIENDS_REQUEST_LIST_REQUEST";
export const USER_FRIENDS_REQUEST_LIST_SUCCESS =
    "USER_FRIENDS_REQUEST_LIST_SUCCESS";
export const USER_FRIENDS_REQUEST_LIST_FAIL = "USER_FRIENDS_REQUEST_LIST_FAIL";

export const USER_GROUP_REQUEST_LIST_REQUEST =
    "USER_GROUP_REQUEST_LIST_REQUEST";
export const USER_GROUP_REQUEST_LIST_SUCCESS =
    "USER_FRIENDS_GROUP_LIST_SUCCESS";
export const USER_GROUP_REQUEST_LIST_FAIL = "USER_GROUP_REQUEST_LIST_FAIL";

export const USER_FRIENDS_REQUEST_DECLINE_REQUEST =
    "USER_FRIENDS_REQUEST_DECLINE_REQUEST";
export const USER_FRIENDS_REQUEST_DECLINE_SUCCESS =
    "USER_FRIENDS_REQUEST_DECLINE_SUCCESS";
export const USER_FRIENDS_REQUEST_DECLINE_FAIL =
    "USER_FRIENDS_REQUEST_DECLINE_FAIL";
export const USER_FRIENDS_REQUEST_DECLINE_RESET =
    "USER_FRIENDS_REQUEST_DECLINE_RESET";

export const USER_FRIENDS_REQUEST_ACCEPT_REQUEST =
    "USER_FRIENDS_REQUEST_ACCEPT_REQUEST";
export const USER_FRIENDS_REQUEST_ACCEPT_SUCCESS =
    "USER_FRIENDS_REQUEST_ACCEPT_SUCCESS";
export const USER_FRIENDS_REQUEST_ACCEPT_FAIL =
    "USER_FRIENDS_REQUEST_ACCEPT_FAIL";
export const USER_FRIENDS_REQUEST_ACCEPT_RESET =
    "USER_FRIENDS_REQUEST_ACCEPT_RESET";

export const USER_GROUP_CREDIT_DEBT_REQUEST = "USER_GROUP_CREDIT_DEBT_REQUEST";
export const USER_GROUP_CREDIT_DEBT_SUCCESS = "USER_GROUP_CREDIT_DEBT_SUCCESS";
export const USER_GROUP_CREDIT_DEBT_FAIL = "USER_GROUP_CREDIT_DEBT_FAIL";

export const USER_CREDIT_REQUEST = "USER_CREDIT_REQUEST";
export const USER_CREDIT_SUCCESS = "USER_CREDIT_SUCCESS";
export const USER_CREDIT_FAIL = "USER_CREDIT_FAIL";

export const USER_DEBT_REQUEST = "USER_DEBT_REQUEST";
export const USER_DEBT_SUCCESS = "USER_DEBT_SUCCESS";
export const USER_DEBT_FAIL = "USER_DEBT_FAIL";

export const USER_FRIEND_NOT_MEMBER_GROUP_SEARCH_REQUEST =
    "USER_FRIEND_NOT_MEMBER_GROUP_SEARCH_REQUEST";
export const USER_FRIEND_NOT_MEMBER_GROUP_SEARCH_SUCCESS =
    "USER_FRIEND_NOT_MEMBER_GROUP_SEARCH_SUCCESS";
export const USER_FRIEND_NOT_MEMBER_GROUP_SEARCH_FAIL =
    "USER_FRIEND_NOT_MEMBER_GROUP_SEARCH_FAIL";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";
export const USER_PROFILE_UPDATE_RESET = "USER_PROFILE_UPDATE_RESET";
