export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_FRIENDS_LIST_REQUEST = "USER_FRIENDS_LIST_REQUEST";
export const USER_FRIENDS_LIST_SUCCESS = "USER_FRIENDS_LIST_SUCCESS";
export const USER_FRIENDS_LIST_FAIL = "USER_FRIENDS_LIST_FAIL";

export const USER_FRIENDS_SEARCH_REQUEST = "USER_FRIENDS_SEARCH_REQUEST";
export const USER_FRIENDS_SEARCH_SUCCESS = "USER_FRIENDS_SEARCH_SUCCESS";
export const USER_FRIENDS_SEARCH_FAIL = "USER_FRIENDS_SEARCH_FAIL";

export const USER_FRIENDS_DELETE_REQUEST = "USER_FRIENDS_DELETE_REQUEST";
export const USER_FRIENDS_DELETE_SUCCESS = "USER_FRIENDS_DELETE_SUCCESS";
export const USER_FRIENDS_DELETE_FAIL = "USER_FRIENDS_DELETE_FAIL";
export const USER_FRIENDS_DELETE_RESET = "USER_FRIENDS_DELETE_RESET";
