# Generated by Django 4.2 on 2023-08-08 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
