# Generated by Django 4.2 on 2023-09-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="isEvenlySplit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="isTypeSettle",
            field=models.BooleanField(default=False),
        ),
    ]
