# Generated by Django 4.2 on 2023-08-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_trip_createdat_trip_description_alter_trip_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
    ]
