# Generated by Django 4.2 on 2023-08-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_group_groupinvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
